version: '3'

services:
  hemppa:
    container_name: hemppa
    image: 'hemppa:latest'
    build: '.'
    restart: always
    environment:
      - MATRIX_ACCESS_TOKEN
      - MATRIX_USER
      - MATRIX_SERVER
      - JOIN_ON_INVITE
      - BOT_OWNERS
      - DEBUG
      - TZ
    volumes:
      - ${PWD}/config/:/bot/config
      - ${PWD}/credentials.json:/bot/credentials.json
      - ${PWD}/token.pickle:/bot/token.pickle
      - ${PWD}/welcome.md:/bot/welcome.md

    stop_signal: SIGINT
